title: Learning Github Pages
author: Athang Gupte
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to make Github Pages site using Jekyll on Github Learning Lab

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  xdevapps # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# Themes
theme: minima
